### ISSUE TITLE
flask compiling error

### ISSUE THREAD

**Issue by mohibm708** [Allen-ISD-Computer-Science/REPO_allencsforum.org_2024#19]
Traceback (most recent call last):
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/main.py", line 5, in <module>
    import awsController
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/awsController.py", line 3, in <module>
    from boto.dynamodb2.fields import HashKey, RangeKey, GlobalAllIndex
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/.venv/lib/python3.11/site-packages/boto/dynamodb2/fields.py", line 1, in <module>
    from boto.dynamodb2.types import STRING
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/.venv/lib/python3.11/site-packages/boto/dynamodb2/types.py", line 4, in <module>
    from boto.dynamodb.types import NonBooleanDynamizer, Dynamizer
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/.venv/lib/python3.11/site-packages/boto/dynamodb/types.py", line 30, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by mohibm708** [comment]
i'm pretty all the necessary packages got installed thanks to your advice. despite a new error of:

```
Traceback (most recent call last):
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/main.py", line 5, in <module>
    import awsController
  File "/home/mohibullah-meer/Projects/REPO_allencsforum.org_2024/static/steam_life/awsController.py", line 16, in <module>
    calendarTable = Table('STEAM-APP-Calendar', connection=conn)
                                                           ^^^^
NameError: name 'conn' is not defined
```

i think the situation has improved, since this is just a bug related to how the files themselves are written. is "conn" the correct variable name?

**Comment by saip9** [comment]
To fix the error, I need to send you secret keys for the AWS database and the application.

**Comment by saip9** [comment]
Also, always remove these secret keys and code when you push the code to GitHub as these can be used to hack into the application.
